version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: elevenia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5321:5432'
    volumes:
      - app-db:/var/lib/postgresql/data

  app:
    container_name: app
    image: app:latest
    build:
      context: .
    environment:
      NODE_ENV: production
      POSTGRES_DB: elevenia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DIALECT: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5321
    ports:
      - '3000:8080'
    depends_on:
      - postgres
    volumes:
      - ./:/home/app
      - /home/app/node_modules

volumes:
  app-db: {}
    # driver: local
